name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qtdeclarative5-dev \
            qtquickcontrols2-5-dev \
            qtbase5-dev \
            libprotobuf-dev \
            protobuf-compiler \
            cmake \
            g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          sudo update-alternatives --config gcc

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make
